version: 'latest'

services:
  postgres:
    image:  postgres:12-alpine3.18
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9df78dfg8d79g